=== AbdoulAzizBerthe/Web-Service/Devoir/XML/releve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 

<xsd:element name="releve">
    <xsd:complexType>
        <xsd:sequence>
            <xsd:element name="dateReleve" type="xsd:date"></xsd:element>
            <xsd:element name="solde" type="xsd:float"></xsd:element>
            <xsd:element name="operations"  type="Ty_OP"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="RIB" type="xsd:decimal" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:element>
    <xsd:complexType name="Ty_OP">
        <xsd:sequence>
           <xsd:element name="operation" maxOccurs="unbounded" type="ty_op"></xsd:element>
        </xsd:sequence>
        <xsd:attribute name="dateDebut" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="dateFin" type="xsd:date" use="required"></xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="ty_op">
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="CREDIT"></xsd:enumeration>
                    <xsd:enumeration value="DEBIT"></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="date" type="xsd:date" use="required"></xsd:attribute>
        <xsd:attribute name="montant" type="xsd:float" use="required"></xsd:attribute>
        <xsd:attribute name="decription" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="Vers Espece"></xsd:enumeration>
                    <xsd:enumeration value="Cheque Guichet"></xsd:enumeration>
                    <xsd:enumeration value="Prelevement Assurence"></xsd:enumeration>
                    <xsd:enumeration value="Virement ..."></xsd:enumeration>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== AbdoulAzizBerthe/Web-Service/Devoir/XML/xsdXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<releve xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Users/NANOTEK/TP/Web-Service/Devoir/XML/releve.xsd" RIB="2325638">
    <dateReleve>2021-11-10</dateReleve>
    <solde>14000</solde>
    <operations dateDebut="2021-01-01" dateFin="2021-01-30">
        <operation type="CREDIT" date="2021-01-01" montant="9000" decription="Cheque Guichet"/>
        <operation type="CREDIT" date="2021-01-01" montant="9000" decription="Cheque Guichet"/>
        <operation type="DEBIT" date="2021-01-15" montant="120" decription="Prelevement Assurence"/>
        <operation type="CREDIT" date="2021-01-25" montant="70000" decription="Virement ..."/>
    </operations>
</releve>
